---
- hosts: all
  tasks:
  - name: Add ssh keys for admins
    authorized_key:
      user: fedora
      key: "{{ lookup('file', 'files/' + item + '.pub') }}"
    with_items:
    - misc
    - jberkus
    - scollier
    - rcook

- hosts: bastion
  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - ansible
    - libselinux-python

  - name: Checkout openshift-ansible
    git:
      repo: https://github.com/openshift/openshift-ansible.git
      dest: /opt/openshift-ansible
      version: openshift-ansible-3.3.13-1

  - name: Copy hosts file
    copy:
      src: hosts
      dest: /etc/ansible/hosts

  - name: Create ssh keys
    user:
      name: root
      generate_ssh_key: yes
    register: key

- hosts: all
  tasks:
  - name: Add key to deploy
    authorized_key:
      user: fedora
      key: "{{ hostvars['bastion']['key']['ssh_public_key'] }}"
