---
- hosts: all
  tasks:
  - name: Add ssh keys for admins
    authorized_key:
      user: fedora
      key: "{{ lookup('file', 'files/' + item + '.pub') }}"
    with_items:
    - misc
    - jberkus
    - scollier
    - rcook

- hosts: bastion
  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - ansible
    - libselinux-python
    # needed or ansible version check fail
    - pyOpenSSL
  - name: Checkout openshift-ansible
    git:
      repo: https://github.com/openshift/openshift-ansible.git
      dest: /opt/openshift-ansible
      version: openshift-ansible-3.3.13-1

  - name: Copy hosts file
    copy:
      src: hosts
      dest: /etc/ansible/hosts

  - name: Create ssh keys
    user:
      name: root
      generate_ssh_key: yes
    register: key

  - name: Install dnsmasq
    package:
      name: dnsmasq
      state: present

  - service:
      name: dnsmasq
      state: started
      enabled: True

- hosts: all
  tasks:
  - name: Add key to deploy
    authorized_key:
      user: fedora
      key: "{{ hostvars['bastion']['key']['ssh_public_key'] }}"
  - name: Install needed packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
    - libsemanage-python
    - dbus-python

  - name: Copy system hosts file
    template:
      src: hosts.system
      dest: /etc/hosts

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}.fosp"

  - name:
    copy:
      dest: /etc/resolv.conf
      content: "search fosp\nnameserver 172.25.160.12\n"
