---
- hosts: all
  roles:
  - admin_ssh_keys

- hosts: bastion
  tasks:
  - name: Install required packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - ansible
    - libselinux-python
    # needed or ansible version check fail
    - pyOpenSSL
  - name: Checkout openshift-ansible
    git:
      repo: https://github.com/openshift/openshift-ansible.git
      dest: /opt/openshift-ansible
      version: openshift-ansible-3.3.35-1

  - name: Create directories for holding vars
    file:
      name: "/etc/ansible/{{ item }}"
      state: directory
    with_items:
    - group_vars
    - group_vars/masters

  - name: Copy ansible files
    copy:
      src: "{{ item }}"
      dest: "/etc/ansible/{{ item }}"
    with_items:
    - hosts
    - group_vars/masters/example.yml

  - name: Create ssh keys
    user:
      name: root
      generate_ssh_key: yes
    register: key

  - copy:
      src: files/deploy.sh
      dest: /usr/local/bin/deploy.sh
      mode: 0755

- hosts: all
  tasks:
  - name: Add key to deploy
    authorized_key:
      user: fedora
      key: "{{ hostvars['bastion']['key']['ssh_public_key'] }}"
  - name: Install needed packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
    - libsemanage-python
    - dbus-python

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}.fosp"

  - name: Copy system hosts file
    template:
      src: hosts.system
      dest: /etc/hosts

  - name:
    copy:
      dest: /etc/resolv.conf
      content: "search fosp\nnameserver 172.25.160.20\n"

- hosts: bastion
  roles:
  - haproxy_bastion
  - dnsmasq 
