---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - haproxy

- name: Deploy haproxy backend
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Start haproxy
  service:
    name: haproxy
    state: started
    enabled: True

